AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/**/*
    - config/initializers/**/*
    - vendor/**/*
    - tmp/**/*

## Setting some preferences...

DotPosition:
  EnforcedStyle: trailing

## Disabling some cops:

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

# Disabling cops that came with an upgraded version of Rubocop -- feel free
# to fix and re-enable these in the future, pending preference.

Bundler/OrderedGems:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/For:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# Using explicit #freeze seems to not get picked up by this cop?
FrozenStringLiteralComment:
  Enabled: false

# Causes issues with Rails' #update method
RedundantMerge:
  Enabled: false

StructInheritance:
  Enabled: false

MultilineMethodCallIndentation:
  Enabled: false

MultilineOperationIndentation:
  Enabled: false

GuardClause:
  Enabled: false

# https://github.com/bbatsov/ruby-style-guide/issues/270 kinda sums it up
Lambda:
  Enabled: false

## We'll use CodeClimate or another tool to track the following:

MethodLength:
  Enabled: false

PerceivedComplexity:
  Enabled: false

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false
